const facts = [
  "A dancing banana may brighten your day.",
  "A nap in your near future will feel like a vacation.",
  "Someone out there is thinking about cookies. It might be you!",
  "Today's lucky number is… 7. Or maybe 8. We're not sure.",
  "Beware of giggles—they are very contagious!",
  "You will soon be famous… to your pet.",
  "Don't trust spaghetti—it's always up to something noodly.",
  "Someone will tell you a very silly joke today.",
  "You will step on a squeaky toy at the most unexpected time.",
  "You're about to invent a new dance move. Use it wisely.",
  "You are secretly awesome at pretending to be a robot.",
  "A penguin will waddle into your dreams tonight with important news!",
  "You will soon meet a dog who thinks you're their favorite human.",
  "Did you know? A group of flamingos is called a ‘flamboyance!'",
  "You might be part sloth… especially on Monday mornings.",
  "A sneaky squirrel is watching you. Probably from a tree.",
  "Fun fact: Octopuses have three hearts. That's a lot of love!",
  "You will laugh like a hyena today—possibly during lunch.",
  "Cows have best friends. So should you!",
  "Elephants can't jump—but you can! That makes you special!",
  "A chameleon thinks you're super colorful—even when you're not.",
  "Kangaroos can't walk backward. But they never need to!",
  "Owls can turn their heads almost all the way around. Don't try this at home.",
  "A big belly laugh is headed your way!",
  "Today, your socks will be extra lucky.",
  "Adventure is hiding behind the next door… maybe the fridge.",
  "You will become an expert in silly faces today.",
  "A great idea is bouncing toward your brain right now!",
  "You will win a dance-off with your shadow.",
  "You will learn something new and awesome very soon!",
  "Your next yawn might sound like a lion's roar.",
  "You will draw the best doodle ever tomorrow.",
  "The universe agrees: you're totally awesome.",
  "Sea otters hold hands when they sleep so they don't float away from each other.",
  "Parrots can dance to music! They actually have rhythm.",
  "A snail can sleep for up to three years. Lazy bones!",
  "Giraffes only need 5 to 30 minutes of sleep each day.",
  "Sharks existed before dinosaurs. That's over 400 million years ago!",
  "Cows have best friends and get stressed when they are separated.",
  "An ostrich's eye is bigger than its brain.",
  "Tigers have striped skin, not just striped fur.",
  "A flamingo's pink color comes from the food they eat—mostly shrimp!",
  "A crocodile can't stick its tongue out.",
  "A group of rhinos is called a crash.",
  "Bees can recognize human faces.",
  "Bats always turn left when exiting a cave.",
  "The heart of a blue whale is as big as a small car.",
  "Koalas sleep for up to 20 hours a day.",
  "Cats can make over 100 different sounds. Dogs? Just about 10.",
  "Sloths can hold their breath longer than dolphins.",
];

export const getFact = () => {
  return facts[Math.floor(Math.random() * facts.length)];
};
